services:
    - type: web
      name: nango-server
      env: docker
      repo: https://github.com/R0-Software/nango-render
      plan: free 
      branch: main
      envVars:
          - fromGroup: Nango
          - key: NANGO_DB_NAME
            fromDatabase:
                name: nango-db
                property: database
          - key: NANGO_DB_PASSWORD
            fromDatabase:
                name: nango-db
                property: password
          - key: NANGO_DB_HOST
            fromDatabase:
                name: nango-db
                property: host
          - key: NANGO_DB_PORT
            fromDatabase:
                name: nango-db
                property: port
          - key: NANGO_DB_SSL
            value: TRUE
          - key: SERVER_PORT
            value: 443
          - key: NANGO_DASHBOARD_USERNAME
            value: "admin"
          - key: NANGO_DASHBOARD_PASSWORD
            generateValue: true
          - key: TELEMETRY
            value: false
databases:
    - name: nango-db
      databaseName: nango
      user: nango
      plan: free 
